language: bash
script:
- cat sample_travis_output.txt
after_success:
# get lucee version string
- sleep 5s && curl -s "https://api.travis-ci.org/v3/job/${TRAVIS_JOB_ID}/log.txt?deansi=true" > travis_output.log
- export LUCEE_VERSION=$(grep -oP "(?<=\[INFO\] Building Lucee Loader Build )(\d+\.\d+\.\d+\.\d+(.*)?)" travis_output.log)
# make API call
- echo "$LUCEE_VERSION"
