language: bash
script:
- cat travis_output.log
after_success:
- curl -s "https://api.travis-ci.org/v3/job/${TRAVIS_JOB_ID}/log.txt?deansi=true" > travis_output.log
- export LUCEE_VERSION=$(grep -oP "(?<=\[INFO\] Building Lucee Loader Build )(\d+\.\d+\.\d+\.\d+(.*)?)" travis_output.log)
- echo "----"
- echo "$LUCEE_VERSION"
- echo "----"
